Homework 3. Task 1. Ri
xImoZA/python_spbu_TP23 pull request #19
Opened 2023-10-09 20:32 UTC by xImoZA

add homework 3, task 1

2023-10-10 19:44 UTC, xImoZA commented
я не придумала, как выдать ошибку, если параметров < arity или если arity == 0 и вводятся еще параметры. exit() прекращает полностью выполнение кода, но если просто вернуть False или None, а в функцию задаются параметры, то выдаст ошибку. Все это можно решить, если есть какой-то метод проверки того, что вызов функции без параметров зайдет в функцию, а не выдаст <function "функция" at 0x7f39886872e0>, но я такого метода в интернете не нашла

2023-10-16 19:25 UTC, toadharvard requested changes
В остальном lgtm

2023-10-16 19:25 UTC, toadharvard commented on src/homeworks/homework-3/homework-3_task-1.py
> +        exit("Uncorrected arity")
Слишком жестко выходишь. Лучше raise ValueError("Arity must be non-negative")

2023-10-16 19:25 UTC, toadharvard commented on src/homeworks/homework-3/homework-3_task-1.py
> +                "Uncorrected input: The number of arguments does not correspond to arity"
Тут тоже

2023-10-16 19:25 UTC, toadharvard commented on src/homeworks/homework-3/homework-3_task-1.py
> +            exit(
И тут

2023-10-16 19:25 UTC, toadharvard commented on src/homeworks/homework-3/homework-3_task-1.py
> +        exit("Uncorrected arity")
тут тоже)

2023-10-16 19:27 UTC, toadharvard commented
> я не придумала, как выдать ошибку, если параметров < arity или если arity == 0 и вводятся еще параметры. exit() прекращает полностью выполнение кода, но если просто вернуть False или None, а в функцию задаются параметры, то выдаст ошибку. Все это можно решить, если есть какой-то метод проверки того, что вызов функции без параметров зайдет в функцию, а не выдаст <function "функция" at 0x7f39886872e0>, но я такого метода в интернете не нашла

Для ошибок хорошо подходят exceptions. В среду расскажу, а пока попробуй применить из той информации, что в доке найдешь, будет полезно :)

2023-10-17 09:30 UTC, SpirinEgor requested changes
Согласен про exit
Раз уж начинаем потихоньку внедрять исключения, то и тут можно. Заменить все exit на выброс ValueError вполне валидно

2023-10-17 19:29 UTC, toadharvard requested changes

2023-10-17 19:29 UTC, toadharvard commented on src/homeworks/homework-3/homework-3_task-1.py
> +            except TypeError:
Попытка хорошая, но лучше не допускать возникновения TypeError в принципе. Т.е тупо проверять, что если арити меньше 0, то raise ValueErrro

2023-10-17 19:43 UTC, toadharvard approved these changes

2023-10-19 13:24 UTC, SpirinEgor approved these changes

2023-10-19 13:24 UTC, merged