Homework 5. Task 3. Ri
xImoZA/python_spbu_TP23 pull request #24
Opened 2023-10-25 14:34 UTC by xImoZA

add homework 5, task 3 and its realization

2023-10-29 20:55 UTC, toadharvard commented
>  realization
Implementation звучит в разы лучше и корректнее , используй его

2023-10-29 21:01 UTC, toadharvard requested changes
В общем и целом милая semi-immutable реализация очереди, исправишь комменты -- будет хорошо

2023-10-29 21:01 UTC, toadharvard commented on src/homeworks/homework_5/usege_queue.py
> +from src.homeworks.homework_5.homework_5_task_3 import *
поэтому надо нормально называть модули, чтобы не получались вот такие страшные названия

2023-10-29 21:01 UTC, toadharvard commented on src/homeworks/homework_5/homework_5_task_3.py
> +    head: QueueElement
Корректный тип: head: QueueElement | None или head: Optional(QueueElement)
tail то же самое

2023-10-29 21:01 UTC, toadharvard commented on src/homeworks/homework_5/homework_5_task_3.py
> +def size(queue):
Функции -- глаголы. Все вокруг должно быть с первым словом глаголом get_size, is_empty и т.п

2023-10-29 21:03 UTC, toadharvard commented
Коммит ксатти ни о чем не говорит, представь смержится 10 Initial commit по числу домашек, нихрена не будет понятно

2023-11-02 07:50 UTC, toadharvard approved these changes

2023-11-03 15:29 UTC, SpirinEgor approved these changes

2023-11-03 15:29 UTC, merged