Homework 6. Task 1. Ri
xImoZA/python_spbu_TP23 pull request #34
Opened 2023-11-19 15:56 UTC by xImoZA

add avl, test 1 (shopping) and tests

2023-11-30 18:51 UTC, toadharvard requested changes
Внутренние функции часто очень странно называются. Все остальное вполне ничего. Читаемо. 
Возможно тестам не хватает проверки вставкой множества случайных значений (лучше по фикс. seed) и проверки инвариантов дерева.

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +        def items_recursion(cur_map: TreeNode[K, V], other_func: Callable) -> None:
Лучше перенести объяление на уровень items. Желательно сразу после объявления get_items. Так читаемее.

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +def get_items(tree: TreeMap[K, V], func: Callable) -> list[(K, V)]:
Из нейминга неясно для чего func в этой функции.

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +                if node is not cur_map:
nit: Стоит поменять местами условия if и else, чтобы не было двойного отрицания при понимании

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +        def items_recursion(cur_map: TreeNode[K, V], other_func: Callable) -> None:
other_func не нужен, можно использовать замыкания и просто писать func и тем самым не передавать лишний параметр в item_recursion

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +        elif cur_key > cur_node.key:
Лучше if

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +        elif cur_node.left_child is None:
Лучше if

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +        elif cur_node.right_child is None:
Лучше if

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +        cur_map = TreeNode(
Почему cur_map, если вроде Node

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +    def remove_recursion(
Объявление функции лучше сразу после def remove.

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +    for key in get_items(tree, postorder_comparator):
```suggestion
    for (key, _ ) in get_items(tree, postorder_comparator):
```

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +        remove(tree, key[0])
```suggestion
        remove(tree, key)
```

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +        return cur_min
Копипаста

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +        return cur_min
Вот этого.

Можно вынести в приватную функцию, куда можно было бы передать компаратор

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/AVL.py
> +    elif max_key == key:
Лучше if

2023-11-30 18:51 UTC, toadharvard commented on src/homeworks/homework_6/task_1.py
> +        print(f"File {log_file} not exist")
Мне кажется странным продолжать работу, когда условия существования и/или несуществования файлов не выполнились

2023-11-30 18:51 UTC, toadharvard commented on tests/homeworks/homework_6/test_AVL/test_AVL.py
> +def get_tree(*args):
Название не очень говорящее.

2023-11-30 18:51 UTC, toadharvard commented on tests/homeworks/homework_6/test_AVL/test_AVL.py
> +    for node in args:
```suggestion
    for (key, value) in args:
```

2023-11-30 18:51 UTC, toadharvard commented on tests/homeworks/homework_6/test_shopping/test_homework-6_1.py
> +def get_tree(*args):
Копипаста?

2023-11-30 18:51 UTC, toadharvard commented on tests/homeworks/homework_6/test_shopping/test_homework-6_1.py
> +                read_file("tests/homeworks/homework_6/test_shopping/shop_logs.txt")[0],
вынеси название файла в отдельную переменную

используй [f"{key} {value}\n" for get_items(tree)] перед этим получив tree из read_file. Так читаемее

2023-12-23 19:03 UTC, SpirinEgor requested changes
Хочется адекватный и честный тест на добавление вершин

2023-12-23 19:03 UTC, SpirinEgor commented on src/homeworks/homework_6/AVL.py
> +    value: Optional[V] = None
Кажется это не может быть None, уж без ключа вершина точно не может существовать

2023-12-23 19:03 UTC, SpirinEgor commented on src/homeworks/homework_6/AVL.py
> +    return get_min_in_node(node.left_child)
Лучше циклом, а не рекурсией, незачем лишний раз стек вызовов функций засорять

2023-12-23 19:03 UTC, SpirinEgor commented on src/homeworks/homework_6/AVL.py
> +    return bool(get_node_in_tree(tree.root, key))
Не самая очевидная запись, лучше явно с None проверить

2023-12-23 19:03 UTC, SpirinEgor commented on src/homeworks/homework_6/AVL.py
> +    return get_node_in_tree(tree.root, key).value
Можно избежать двойного обхода дерева

2023-12-23 19:03 UTC, SpirinEgor commented on src/homeworks/homework_6/AVL.py
> +    return get_max_recursion(tree.root)
Аналогично, лучше сделать без рекурсии

2023-12-23 19:03 UTC, SpirinEgor commented on tests/homeworks/homework_6/test_AVL/test_AVL.py
> +        (create_test_tree(), 4, "*", create_test_tree((4, "*"))),
А в чем смысл теста?) По итоге сравнивается, что после put одинаковые деревья, а не что правильно добавлено

2023-12-27 11:33 UTC, SpirinEgor requested changes
Надо тесты добавить

2023-12-27 11:33 UTC, SpirinEgor commented on src/homeworks/homework_6/AVL.py
> +    return True
🥴

2023-12-27 12:46 UTC, SpirinEgor approved these changes

2023-12-27 12:48 UTC, toadharvard approved these changes

2023-12-27 12:48 UTC, merged